### ISSUE TITLE
SDL2 tests fail 't/001_load_all.t .......... Can't locate SDL2/Log.pm'

### ISSUE THREAD

**Issue by KohaAloha** [PerlGameDev/SDL2#1]
hi

the tests seem to failing...

bash-3.2$ git log -1
commit a609b80201c00952cc2f9eec14c4513e60a7a56d
Author: Kartik Thakore thakore.kartik@gmail.com
Date:   Thu May 2 19:48:55 2013 -0400

```
Added missing files for log
```

bash-3.2$ prove
t/001_load_all.t .......... Can't locate SDL2/Log.pm in @INC (@INC contains: /Users/mason/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.2/darwin-2level /Users/mason/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.2 /Users/mason/perl5/perlbrew/perls/perl-5.16.2/lib/5.16.2/darwin-2level /Users/mason/perl5/perlbrew/perls/perl-5.16.2/lib/5.16.2 .) at t/001_load_all.t line 19.
BEGIN failed--compilation aborted at t/001_load_all.t line 19.
Bailout called.  Further testing stopped:  Could not load all modules
FAILED--Further testing stopped: Could not load all modules

bash-3.2$ tree -f |grep Log.pm

**Comment by kthakore** [comment]
Hi KohaAloha,

Do you have SDL2 installed on Mac? Also what Mac version is this?

**Comment by KohaAloha** [comment]
hiya Kartik
yes, i'm running 10.7.5 (lion)

thanks for the quick fix :)

**Comment by kthakore** [comment]
No worries. Please create issues for features, bugs, etc.

I really would appreciate test cases too!
